language: php
php:
    - 7.2
    - 7.3
    - 7.4

install:
    - composer install

script:
    - php vendor/phpunit/phpunit/phpunit
    - php vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix --diff --dry-run -v
